In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier 
from sklearn.svm import SVC 
from sklearn.model_selection import train_test_split

In [2]:
digits = load_digits()

In [3]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size=0.3)

# **LogisticRegression**

In [4]:
lr = LogisticRegression(solver="liblinear", multi_class="ovr")
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9518518518518518

# **SVM**

In [5]:
svm = SVC(gamma="auto")
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.5092592592592593

# **RandomForest**

In [6]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975925925925926

# **Cross_Validation**

<img src="https://learningds.org/_images/CVDiagram.png" width="900" height="900" />

In [7]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

# LogisticRegression model's score using Cross Validation

In [8]:
cross_val_score(LogisticRegression(solver="liblinear", multi_class="ovr"), digits.data, digits.target, cv=3)# cv(cross validation)= 3 meaning train 3 times 

array([0.89482471, 0.95325543, 0.90984975])

# SVM model's score using Cross Validation

In [9]:
cross_val_score(SVC(), digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [10]:
predictions = cross_val_predict(SVC(), digits.data, digits.target, cv=5)
predictions

array([0, 1, 8, ..., 8, 9, 8])

# RandomForest model's score using Cross Validation

In [11]:
cross_val_score(RandomForestClassifier(n_estimators=100), digits.data, digits.target, cv=3)

array([0.93155259, 0.94991653, 0.93489149])

In [12]:
cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=3)

array([0.93322204, 0.92821369, 0.92821369])

In [13]:
cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=10)

array([0.90555556, 0.96666667, 0.92777778, 0.88333333, 0.92777778,
       0.97222222, 0.95555556, 0.95530726, 0.92178771, 0.91620112])

In [14]:
cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=50)

array([0.94444444, 0.97222222, 1.        , 0.91666667, 1.        ,
       0.97222222, 1.        , 1.        , 1.        , 0.97222222,
       0.94444444, 0.97222222, 0.97222222, 1.        , 0.94444444,
       0.97222222, 0.97222222, 0.94444444, 0.97222222, 0.97222222,
       0.97222222, 0.97222222, 0.97222222, 0.91666667, 0.94444444,
       0.97222222, 1.        , 1.        , 1.        , 1.        ,
       0.91666667, 0.97222222, 1.        , 1.        , 0.97222222,
       0.97222222, 1.        , 0.94444444, 1.        , 1.        ,
       1.        , 1.        , 0.94444444, 0.94444444, 0.86111111,
       0.88888889, 0.94444444, 1.        , 0.94285714, 0.94285714])

In [15]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv=10)

array([0.90555556, 0.97777778, 0.94444444, 0.91111111, 0.95      ,
       0.96111111, 0.97222222, 0.96648045, 0.89944134, 0.93854749])

In [16]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=20)

array([0.88888889, 0.94444444, 0.98888889, 0.98888889, 0.98888889,
       0.97777778, 0.92222222, 0.95555556, 0.95555556, 0.97777778,
       0.95555556, 0.98888889, 0.97777778, 0.97777778, 0.97777778,
       0.98888889, 0.97777778, 0.92134831, 0.94382022, 0.94382022])